# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-11-09 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(max_length=200)),
                ('phone', models.IntegerField(max_length=10)),
                ('name', models.CharField(max_length=200)),
                ('amount', models.IntegerField(max_length=20)),
            ],
        ),
    ]
