# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-11-09 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parserApp', '0004_auto_20171109_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='amount',
            field=models.IntegerField(max_length=200),
        ),
    ]
